[package]
name = "am3k"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.5"
serde = { version = "1.0", features = ["derive"] }
serde_yml = "0.0.10"
serde_json = "1.0.112"
tera = "1.20.0"
thiserror = "1.0"